# Generated by Django 4.2.11 on 2024-04-06 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WongnokRecipe',
            fields=[
                ('auto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image_address', models.TextField()),
                ('ingredient', models.TextField()),
                ('step', models.TextField()),
                ('duration', models.CharField(choices=[('5 to 10 minutes', '5 to 10 minutes'), ('11 to 30 minutes', '11 to 30 minutes'), ('31 to 60 minutes', '31 to 60 minutes'), ('60+ minutes', '60+ minutes')], max_length=50, unique=True)),
                ('cooking_level', models.CharField(choices=[('Rookie', 'Rookie'), ('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('Pro', 'Pro'), ('Master', 'Master'), ('Legend', 'Legend')], max_length=50, unique=True)),
                ('updated_timestamp', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wongnok recipe',
                'verbose_name_plural': 'wongnok recipe(s)',
            },
        ),
    ]
