# Generated by Django 4.2.11 on 2024-04-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wongnokrecipe',
            name='cooking_level',
            field=models.CharField(choices=[('Rookie', 'Rookie'), ('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('Pro', 'Pro'), ('Master', 'Master'), ('Legend', 'Legend')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wongnokrecipe',
            name='duration',
            field=models.CharField(choices=[('5 to 10 minutes', '5 to 10 minutes'), ('11 to 30 minutes', '11 to 30 minutes'), ('31 to 60 minutes', '31 to 60 minutes'), ('60+ minutes', '60+ minutes')], max_length=50),
        ),
    ]
