# Generated by Django 4.2.11 on 2024-04-06 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0002_alter_wongnokrecipe_cooking_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wongnokrecipe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RatingLog',
            fields=[
                ('auto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('0.0', '0.0'), ('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0')], max_length=5)),
                ('created_timestamp', models.DateTimeField()),
                ('rated_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.wongnokrecipe')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rating log',
                'verbose_name_plural': 'rating log(s)',
            },
        ),
    ]
